version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: resalt
      MYSQL_PASSWORD: resalt
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: salt-minion -l info
    depends_on:
      - master

  frontend:
    user: "${UID:-1000}:${GID:-1000}"
    image: node:18-alpine
    volumes:
      - ./frontend:/usr/src/app
    command: /bin/sh -c "cd /usr/src/app && npm install && node ./node_modules/.bin/rollup -c -w"
    ports:
      - "5555:5555"
      - "35730:35730"
  backend:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: resalt-devel
    volumes:
      - ./backend:/usr/src/app
    environment:
      - CARGO_HOME=/tmp/.cargo
      - RUST_LOG_STYLE=always # Add color to logs
    ports:
      - "8000:8000"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
