version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: hibike
      MYSQL_PASSWORD: hibike
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: salt-minion -l info
    depends_on:
      - master
  frontend:
    image: node:18
    volumes:
      - ./frontend:/usr/src/app
    command: bash -c "cd /usr/src/app && npm install && npm run dev"
    ports:
      - "5555:5555"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      - RUST_LOG_STYLE=always
    ports:
      - "8000:8000"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
