version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: resalt
      MYSQL_PASSWORD: resalt
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: salt-minion -l info
    depends_on:
      - master

  frontend:
    user: "${UID:-1000}:${GID:-1000}"
    image: node:18-alpine
    volumes:
      - ./frontend:/usr/src/app
    command: /bin/sh -c "cd /usr/src/app && npm install && node ./node_modules/.bin/rollup -c -w"
    ports:
      - "5555:5555"
      - "35730:35730"
  backend:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./
      dockerfile: Dockerfile
      target: resalt-devel
    volumes:
      - .:/usr/src/app
    environment:
      - CARGO_HOME=/tmp/.cargo
      - RUST_LOG_STYLE=always # Add color to logs
      - RESALT_AUTH_LDAP_ENABLED=${RESALT_AUTH_LDAP_ENABLED:-false}
      - RESALT_AUTH_LDAP_URL=${RESALT_AUTH_LDAP_URL:-}
      - RESALT_AUTH_LDAP_START_TLS=${RESALT_AUTH_LDAP_START_TLS:-false}
      - RESALT_AUTH_LDAP_NO_TLS_VERIFY=${RESALT_AUTH_LDAP_NO_TLS_VERIFY:-false}
      - RESALT_AUTH_LDAP_BIND_DN=${RESALT_AUTH_LDAP_BIND_DN:-}
      - RESALT_AUTH_LDAP_BIND_PASSWORD=${RESALT_AUTH_LDAP_BIND_PASSWORD:-}
      - RESALT_AUTH_LDAP_BASE_DN=${RESALT_AUTH_LDAP_BASE_DN:-}
      - RESALT_AUTH_LDAP_USER_FILTER=${RESALT_AUTH_LDAP_USER_FILTER:-}
      - RESALT_AUTH_LDAP_USER_ATTRIBUTE=${RESALT_AUTH_LDAP_USER_ATTRIBUTE:-}
      - RESALT_AUTH_USER_SESSION_LIFESPAN=${RESALT_AUTH_USER_SESSION_LIFESPAN:-}
      - RESALT_DATABASE_URL=${RESALT_DATABASE_URL:-}
      - RESALT_FRONTEND_PROXY_ENABLED=${RESALT_FRONTEND_PROXY_ENABLED:-true}
      - RESALT_FRONTEND_PROXY_TARGET=${RESALT_FRONTEND_PROXY_TARGET:-http://frontend:5555}
      - RESALT_SALT_API_URL=${RESALT_SALT_API_URL:-https://master:8080}
      - RESALT_SALT_API_DISABLE_TLS_VERIFICATION=${RESALT_SALT_API_DISABLE_TLS_VERIFICATION:-true}
      - RESALT_SALT_API_SYSTEM_SERVICE_TOKEN=${RESALT_SALT_API_SYSTEM_SERVICE_TOKEN:-}
    ports:
      - "8000:8000"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
